---
- name: Ensure MicroK8s is installed
  ansible.builtin.import_tasks: _microk8s.yml

- name: Ensure the MicrK8s plugins are installed
  ansible.builtin.import_tasks: _plugins.yml

# Remote access to kubectl
# (this is questionably written, given that DNS.6 is hard coded)
- name: Ensure the host domain is configured in microk8s
  ansible.builtin.lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    regexp: "^DNS.6 = .*"
    line: "DNS.6 = {{ ansible_fqdn }}"
    insertafter: '^\[ alt_names \]'
  ignore_errors: "{{ ansible_check_mode }}"

## Certificates
# - name: Ensure microk8s certificate folder exists
#   ansible.builtin.file:
#     path: /usr/share/ca-certificates/extra
#     state: directory

# - name: Ensure certificates are in place
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: /usr/share/ca-certificates/extra
#     remote_src: true
#     force: true
#   with_fileglob:
#     - /var/snap/microk8s/current/certs/*ca*.crt

# - name: Trust certificates generated by microk8s
#   ansible.builtin.command: |
#     update-ca-certificates
